#!/usr/bin/env python
"""Extract a Jira issue number form the branch and set that as a default commit
message.

If you want to use this hook you need to manually copy it into `.git/hooks` or
just leave it in `~/.githooks/` and run
`git config --global core.hooksPath ~/.githooks`.

"""

from subprocess import check_output
import sys
import re


def get_current_branch_name():
    return str(check_output(["git", "branch", "--show-current"]).strip())


def get_jira_id_from_string(text: str):
    match = re.search(r"\w{2,3}-\d+", text.upper())
    if match:
        return match.group()
    return ""


def prepend_commit_msg(text:str ):
    """Prepend the commit message with `text`.

    We prepend because we want to keep the default diff output.
    Taken from: https://gist.github.com/lorin/2963131

    """
    msgfile = sys.argv[1]

    with open(msgfile) as f:
        contents = f.read()

    with open(msgfile, 'w') as f:
        f.write(text)
        f.write(contents)


def main():
    branch = get_current_branch_name()
    jira_id = get_jira_id_from_string(branch)
    prepend_commit_msg(f"{jira_id}: ")


if __name__ == "__main__":
    main()
